version: '3.8'
services:
  db:
    platform: linux/x86_64
    container_name: db
    image: mariadb:10.4.14
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatbot
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatuserpassword
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

volumes:
  mariadb_data: